### ISSUE TITLE
Option to omit word break characters from token stream

### ISSUE THREAD

**Issue by bradbesserman** [clipperhouse/uax29#9]
First, thanks for building this!

I'm using the `words` package and I'd like to discard all word break characters and only keep the words themselves.  Would you be open to a PR that adds an option to omit the word break characters from the token stream? I'd prefer to support that setting here rather than forking if possible!

**Comment by clipperhouse** [comment]
Hi, sorry for the late response! I think this package will focus on the spec from [Unicode Annex 29](https://unicode.org/reports/tr29/#Word_Boundaries). That spec doesn't say anything about what constitutes a “word” in normal language, it merely describes how to break between tokens.

There are a few things that are clearly “word break characters” — whitespace, for example. Other stuff like punctuation is not so obvious.

I’d suggest filtering the tokens after segmentation, according you your own criteria for “word”. That should be fairly straightforward with [unicode.Is](https://pkg.go.dev/unicode#Is). Hope this helps.

**Comment by clipperhouse** [comment]
I’ve got something in the works here for filtering: https://github.com/clipperhouse/uax29/commit/33866a772dfea4bb2a9c92d5ce7c94003adbdfa8#diff-69c06b73f6971d396980b49e5e4f84c555f732fe4cdbeb259b4f12dcb079a3d1R58
